pip install nltk
pip install pyreadr
pip install selenium
pip install bs4
pip install openpyxl
pip install xlsxwriter
pip install sklearn
pip install pandas_ml
pip install seaborn
pip install tensorflow